version: '0.8.0'
services:
    adrini:
      build: .
      ports:
        - "5000:5000"
      volumes:
        - .:/app
      command: ["bash","run.sh" ,"2"]
      links:
        - "session"

    session:
      image: redis
      command: ["redis-server", "--requirepass", "pass"]
      ports:
        - "6379:6379"